<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>default</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Unit\InvalidReport.xml" />
    <None Remove="Unit\SampleReport.xml" />
    <None Update=".runsettings">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Unit\InvalidReport.xml" />
    <EmbeddedResource Include="Unit\SampleReport.xml" />
    <None Remove="Unit\GoogleGenerated.xml" />
    <EmbeddedResource Include="Unit\GoogleGenerated.xml" />
    <None Remove="Unit\SparseReport.xml" />
    <EmbeddedResource Include="Unit\SparseReport.xml" />
    <None Remove="Unit\MalformedReport.xml" />
    <EmbeddedResource Include="Unit\MalformedReport.xml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="NUnit" Version="4.6.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DmarcRua\DmarcRua.csproj" />
  </ItemGroup>

</Project>
